project:
  type: website
  output-dir: docs

website:
  reader-mode: true
  repo-url: https://wajidiqbal1.github.io/wajidiqbal1/
  repo-actions: [edit, issue]
  site-url: https://wajidiqbal1.github.io/wajidiqbal1/
  navbar:
    title: false
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: gallery/gallery.qmd
        text: Gallery
      - href: posts.qmd
        text: Blogs
      - text: get in touch!
        menu:
          - icon: linkedin
            text: LinkedIn
            href: https://www.linkedin.com/in/wajid-iqbal-a5b533186/
            target: _blank
          - icon: envelope
            text: email
            href: mailto:wwajidiqbal@gmail.com
      - icon: github
        href: https://github.com/Wajidiqbal1/wajidiqbal1
        target: _blank
  page-footer: 
    background: light
    left: © Copyright 2024, Wajid Iqbal
    right: This website is built with {{< fa heart title="pyaar sy" >}}, [{{< fa brands github title="GitHub" >}}](https://wajidiqbal1.github.io/wajidiqbal1/){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    page-layout: full
    sidebar: false
    theme: 
      - styles.scss
    mainfont: Nunito
    toc: true
