project:
  type: website
  output-dir: docs

website:
  reader-mode: true
  repo-url: https://wajidiqbal1.github.io/wajidiqbal1/
  repo-actions: [edit, issue]
  site-url: https://wajidiqbal1.github.io/wajidiqbal1/
  #favicon: images/capture.png
  #google-analytics: 
    #tracking-id: "G-LW03VL0YTS" #"UA-242992767-1"
    #anonymize-ip: true
  navbar:
    title: false
    #logo: images/capture.png
    #logo-alt: "The name 'sam csik' written in green text. Above 'csik' is a dark green horizontal line, above which sits a green chick icon."
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: gallery.qmd
        text: Gallery
      - href: posts.qmd
        text: Blogs
      - text: get in touch!
        menu:
          - icon: google-scholar
            text: Google Scholar
            href: https://scholar.google.com.pk/citations?user=WQk1k7wAAAAJ&hl=en
            target: _blank
          - icon: linkedin
            text: LinkedIn
            href: https://www.linkedin.com/in/wajid-iqbal-a5b533186/
            target: _blank
          - icon: envelope
            text: email
            href: mailto:wwajidiqbal@gmail.com
      - icon: github
        href: https://github.com/Wajidiqbal1/wajidiqbal1
        target: _blank
  page-footer: 
    background: light
    left: © Copyright 2024, wajid Iqbal
    right: This website is built with {{< fa heart title="dil sy" >}}, [{{< fa brands github title="GitHub octocat logo" >}}](https://wajidiqbal1.github.io/wajidiqbal1/){target=_blank}, [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}

format:
  html:
    page-layout: full
    sidebar: false
    theme: 
      - styles.scss
    mainfont: Nunito
    toc: true
