---
title: "About"
subtitle: "A bit more about me"
title-block-banner: true
---

"I'm a computational biologist (sort of) working on genomics, and I especially enjoys playing around with WES, bulk and single-cell RNA-seq data by applying different workflows and scripts on it. I primarily use R for data wrangling and visualization within the tidyverse ecosystem. Although I've never used Python for any projects so far, it’s definitely on my to-do list. I’m an intermediate-level user of Unix and still pick up new shell tricks almost every month. I also have a great interest in promoting open science and reforming bioinformatics education.

My background is in Biotechnology and Human Genetics. I never imagined that I would switch to a coding-centric Path. I completed my bachelor’s degree in Biotechnology at [International Islamic University, Islamabad, Pakistan](https://www.iiu.edu.pk/) in 2021 and am about to finish my master’s degree there as well. I am passionate about all aspects of bioinformatics and data science. Up until 2020, I didn’t even have a laptop, which made things more challenging. During my undergraduate studies, I received an **F** grade in an "Introduction to Bioinformatics course" because I knew nothing about matrix creation; I thought of it as a puzzle involving algorithms like Needleman-Wunsch and Smith-Waterman. Moreover, my mathematics skills were weak from the start—I used to memorize math questions in school just to pass tests. However, everything changed in 2021 when I attended a workshop on transcriptomics using R. Initially, I was completely terrified of anything related to data, coding, or data science, but thanks to a super supportive community, especially my supervisor [Dr. Asif Mir](https://scholar.google.com.pk/citations?hl=en&user=c28ULKwAAAAJ&view_op=list_works&sortby=pubdate), and some excellent colleagues specifically [Dr.Abrar Hussain](https://www.linkedin.com/in/abrar-hussain-662272187/?original_referer=https%3A%2F%2Fwww%2Egoogle%2Ecom%2F&originalSubdomain=pk) and instructors, I an finding my path in Bioinformatics and Data Science Education and i am absolutely loving it."
